#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -f "/etc/node/.env" ] && . "/etc/node/.env"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -n "$NODE_MANAGER" ] || export NODE_MANAGER="fnm"
[ -n "$NODE_VERSION" ] || export NODE_VERSION="22"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
